config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get :dreamboard, to: "pages#dreamboard"
  get 'dreamboard/:user_id', to: "pages#dreamboard", as: :user_dreamboard
  get :dreamfeed, to: "pages#dreamfeed"

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dreams do
    resources :scenes
    member do
      patch :filtered_scene
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
  has_many :scenes, dependent: :destroy
  validates :content, presence: true
  validates :content, length: { maximum: 400 }
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :dream
  validates :content, presence: true
  has_one_attached :image
  # validates :image_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dreams
  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/dreams_controller.rb
require 'open-uri'
class DreamsController < ApplicationController

  def index
    @dreams = Dream.all
  end

  def filtered_scene
    @dream = Dream.find(params[:id])
    @rejected_scenes = @dream.scenes.reject { |scene| params[:dream][:scenes].include?(scene.id.to_s) }
    @rejected_scenes.each do |scene|
      scene.destroy
    end
    # détruit le rève s'il n'y a aucune scène rattachée
    # c'est ça qui casse le dashboard.
    @dream.destroy if @dream.scenes.empty?

    redirect_to dreamboard_path
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user

    if @dream.save
      if openai_request
        redirect_to dream_scenes_path(@dream)
      else
        @dream.destroy
        render :new, status: :unprocessable_entity, alert: "Please try again"
      end
    else
      render :new, status: :unprocessable_entity, alert: "Please try again"
    end
  end

  def show
    @dream = Dream.find(params[:id])
  end

  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy
    redirect_to dreamboard_url, notice: "dream was successfully destroyed."
  end

  private

  def openai_request
    client = OpenAI::Client.new
    prompt = @dream.content
    request = client.chat(
      parameters: {
          model: "gpt-3.5-turbo",
          messages: [{ role: "user", content: "if you can, split this text in paragraph without adding any word to it, if you cant just write the exact same text : '#{prompt}' "}],
          temperature: 0
      }
    )
    chatgpt_response = request.dig("choices", 0, "message", "content")
    return false if chatgpt_response.nil?
    paragraphs = chatgpt_response.strip.split("\n\n")
    paragraphs *= 3 if paragraphs.size == 1
    paragraphs.each_with_index do |paragraph, index|
      if paragraphs[0] != paragraphs[1]
        if paragraphs[0] == paragraph
          response = client.images.generate(parameters: { prompt: "photography of #{paragraph},kodachrome, fujifilm, hd, 4k.",
          size: "512x512",
          n: 1 }
          )
        else
          new_paragraph = paragraphs[0..index].join(",")
          response = client.images.generate(parameters: { prompt: "photography of #{new_paragraph},kodachrome, fujifilm, hd, 4k.",
          size: "512x512",
          n: 1 }
          )
        end
      else
        response = client.images.generate(parameters: { prompt: "photography of #{paragraph},kodachrome, fujifilm, hd, 4k.",
          size: "512x512",
          n: 1 }
          )
      end

      image_url = response.dig("data", 0, "url")
      scene = Scene.new(content: paragraph, dream: @dream, image_url: image_url)
      file = URI.open(image_url)
      scene.image.attach(io: file, filename: "#{Scene.last.id + 1}.png", content_type: "image/png")
      scene.save!

      # Scene.create!(content: paragraph, dream: @dream, image_url: image_url)


    end
    true
  end

  def dream_params
    params.require(:dream).permit(:content, :character, :ambiance, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dreamboard
    # Dream.where(user: current_user) == current_user.dreams
    if params[:user_id].present?
      @dreams = User.find(params[:user_id]).dreams.order(created_at: :desc)
    else
      @dreams = current_user.dreams.order(created_at: :desc)
    end
  end

  def dreamfeed
    @dreams = Dream.order(created_at: :desc)
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController

  def index
    @dream = Dream.find(params[:dream_id])
    @scenes = @dream.scenes
  end

  def show
    @scene = Scene.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private

  def scenes_params
    params.require(:scene).permit(:image_url, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dreams/index.html.erb
<h1>My profile</h1>
<% @dreams.each do |dream| %>
  <%= cl_image_tag dream.image.key, class:"w-100 h-100", height:600, width:600, crop: :fill %>
  <div class="btn-delete">
  <% if @dream.user == current_user%>
  <%= link_to "",
            dream_path(@dream),
            class: "btn-classic fa-regular fa-trash-can",
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %>
  <% end %>
  </div>
<% end %>

app/views/dreams/new.html.erb
<%= render "shared/navbar" %>
<%= audio_tag("IntroB.mp3", type: "audio/mpeg", autoplay: true) %>

<div data-controller="hiddenloading" class="animate__animated animate__fadeIn animate__slower	">
  <div data-hiddenloading-target="form">
    <div class="container position-relative">
      <div class="mt-5 align-items-center d-flex flex-column">
        <%= simple_form_for(@dream, html: {data: { action: "submit->hiddenloading#show"}}) do |f| %>
          <div data-controller="character-counter countermax mb-1">
            <div>
              <%= f.input :content,
                wrapper_html: { class: "mb-1" },
                input_html: {autofocus: true, data: { action: "keyup->countermax#check", character_counter_target: "input",
                countermax_target: "input" } },
                label_html: { class: "form-label text-secondary fw-bold" }, as: :text, label: false, placeholder: "Dozens of white horses, in a field...  "
              %>

            </div>
            <div class="character-counter">
              <div class="count">
                <span data-countermax-target="counter" data-character-counter-target="counter"></span>/400
              </div>
              <i class="fa-solid fa-circle-info bottom-0"
                data-controller="popover"
                data-bs-toggle="popover"
                data-bs-trigger="hover"
                data-html="true"
                data-bs-placement="right"
                title="Tips and best practice"
                data-bs-content="Reminder: You can't use more than 400 char.

                - Avoid Being Too Vague
                - Write short sentences, and use commas.
                - Make sure to describe precisely your dream with basic elements : place, time of the day, characters involved etc.
                Favor Singular Nouns Or Specific Numbers
                - You should avoid using negative terms and simply state exactly what you want regarding colors, materials, and shapes.
                - Avoid using 'I'. ex: 'I was in the middle of the desert'. You might write 'A men/women/child in the middle of the desert' instead.
                - In the same way don't use specific terms such as 'My mom' or 'My brother'.">
              </i>
            </div>
          </div>

          <div class="pulse-container d-flex justify-content-center mt-4">
            <button type="submit" name="commit" class="pulse-button" data-disable-with="Create Dream">
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="hiddenloading d-none d-flex justify-content-center align-items-center" data-hiddenloading-target="loading" style="height: 85vh; font-size:2em; margin-left:50px; margin-right:50px;">
  <%= audio_tag("Loading.mp3", type: "audio/mpeg", loop: true,  'data-hiddenloading-target': "bouclodio") %>
    <%# Quantity should be the same in Sass %>
    <%# <div data-hiddenloading-target="text" class="waiting-text"></div> %>

  <%# la super icone de dreamer %>
  <div class="loading2">
    <svg width="250px" height="250px" viewBox="0 0 187.3 93.7" preserveAspectRatio="xMidYMid meet">
    <path id="infinity-outline" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
          d="M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
    <path id="infinity-bg" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
          d="M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
    </svg>
  </div>
  <div class="loading">
    <svg width="250px" height="250px" viewBox="0 0 187.3 93.7" preserveAspectRatio="xMidYMid meet">
    <path id="infinity-outline" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
          d="M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
    <path id="infinity-bg" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
          d="M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
    </svg>
  </div>

  <%# fireflys %>
  <div>
    <%# Quantity should be the same in Sass %>
    <% quantity = 25 %>
    <% for i in 1..quantity do %>
      <div class="firefly"></div>
    <% end %>
  </div>

</div>

app/views/dreams/show.html.erb
<%= render "shared/navbar" %>

<div data-controller="dream" style="height: 93vh; overflow: auto;">

  <%# image sélectionnée %>
  <div id="selected-image" data-dream-target="selectedImage">
    <%= cl_image_tag @dream.scenes.first.image.key%>
  </div>

  <%# slider des scenes %>
  <div class="dreams">
    <div class="dreams_content_thumb">
      <% if @dream.scenes.first && @dream.scenes.first.image.attached? %>
        <% @dream.scenes.each do |scene| %>
          <div class="dreams_dream-thumb" data-dream-target="dream" data-action="click->dream#selectImage">
            <div class="dreams_dream_image_thumb">
              <%= cl_image_tag scene.image.key %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# dream.content %>

  <div class="dreams_texte">
    <p id="dream-text"> <%= @dream.content.capitalize %></p>
  </div>

  <div class="dreamboard-footer d-flex justify-content-center">
    <%= link_to "<i id='fleches-show' class='fa-solid fa-xmark'></i>".html_safe, :back %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DREAMER</title>
    <%= render 'shared/ios_pwa_links' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#000000">

  </head>

  <body class="page-body">
  <canvas id="gradient-canvas" data-controller="gradient" data-transition-in></canvas>
    <%# navbar inutile pour le moment %>
    <%# <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

<%# # ligne à rentrer pour distinguer class selon page affichée (via l'action) %>
<%# <%=action_name=="home" ? "spectrum-background" : "spectrum-background-general"  %>

app/views/pages/dreamboard.html.erb
<%= render "shared/navbar" %>

  <div class="dreams">
    <div class="dreams_content">
      <% @dreams.each do |dream| %>
        <% if dream.scenes.first && dream.scenes.first.image.attached? %>
          <div class="dreams_dream" data-dreams-target="dream">
            <%= link_to dream_path(dream), class:"text-decoration-none" do %>
              <div class="dreams_dream_image" >
                <%= cl_image_tag dream.scenes.first.image.key, crop: :fill %>
              </div>

              <div class="dreams_title">
                <p id="excerpt"> <%= dream.content.capitalize %></p>
              </div>
<div class="d-flex justify-content-center ml-4">
          <div class="btn-delete">
                <% if dream.user == current_user%>
                <%= link_to "",
                          dream_path(dream),
                          class: "fa-regular fa-trash-can",
                          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
                        %>
                <% end %>
          </div>
</div>
              </div>
            <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/pages/dreamfeed.html.erb
<%= render "shared/navbar" %>


  <div class="grid no-scrollbar ">
    <% @dreams.each do |dream| %>
      <% if dream.scenes.first && dream.scenes.first.image.attached? %>
        <div data-controller="dreamfeed">
          <div class="dreams_dreamfeed_image_thumb" data-action="click->dreamfeed#bigimage">
            <%= cl_image_tag dream.scenes.first.image.key, crop: :fill, class: "imggrid" %>
          </div>
          <div class="big-image d-none" data-dreamfeed-target="showbigimage" data-action="click->dreamfeed#closeimage turbo:before-cache@window->dreamfeed#close">
            <%= link_to dream_path(dream) do %>
              <%= cl_image_tag dream.scenes.first.image.key, crop: :fill, class:"img100", width:390, height:390 %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/pages/home.html.erb
<div class="container" data-controller="homepage" data-action="click->homepage#hide">
  <div id="dreamer-intro" class="container-home">
    <div data-homepage-target="title" class="animate__animated animate__fadeIn ">
      <h1>Dreamer</h1>
    </div>
    <%= audio_tag("Intro.mp3", type: "audio/mpeg", 'data-homepage-target': "music") %>
    <h1><span class="d-none" data-homepage-target="message"></span></h1>
  </div>
</div>

app/views/scenes/index.html.erb
<div class="container mb-5 scene-container">

  <h2 class="pt-4 mx-auto text-center scene-wrapper-title">Select images</h2>
  <div class="scene-wrapper-form">
    <%= simple_form_for(@dream, url: filtered_scene_dream_path(@dream), method: :patch) do |f|%>
      <%= f.input :scenes, collection: @scenes, as: :check_boxes,
          collection_wrapper_tag: 'div',
          label: "",
          collection_wrapper_class: 'scene-wrapper',
          item_wrapper_class: 'scene-item',
          input_html: {class: 'scene-selector d-none'},
          label_method: lambda { |b| "<i class='fa-regular fa-circle-check'></i>".html_safe + cl_image_tag(b.image.key) } %>

        <%= f.submit "Save", class: 'dreambtn btn-start displayed mb-2 scene-wrapper-submit' %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<!-- app/views/shared/_ios_pwa_links.html.erb -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="nav-wrapper" data-controller="toggle-element">
  <div class="navblock d-flex justify-content-between p-4">
    <div class="dots d-flex flex-column justify-content-center">
        <i class="fa-solid fa-ellipsis" data-action="click->toggle-element#toggle turbo:before-cache@window->toggle-element#close"></i>
    </div>
    <div class="logo d-flex flex-column justify-content-center">
      <%= link_to root_path do %>
      <%= image_tag "logo-home.png", style:"width: 40px;"%>
      <% end %>
    </div>
  </div>

  <aside class="sidebar" data-toggle-element-target="element">

    <nav class="sidebar__menu">
      <%= link_to "New dream", new_dream_path %>
      <%= link_to "Dreamboard", dreamboard_path %>
      <%= link_to "Feed", dreamfeed_path %>
      <%# lien vers la page "profile", à définir %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </nav>

    <label for="menu-control" class="sidebar__close" data-action="click->toggle-element#close"></label>
  </aside>
</div>